name: juju-db
version: '4.4.2'
summary: MongoDB object/document oriented database used internally by Juju.
description: |
  MongoDB object/document oriented database used internally by Juju.
confinement: strict
grade: stable
base: core20
license: AGPL-3.0

apps:
  daemon:
    command: commands/daemon.start
    stop-timeout: 600s
    restart-condition: on-failure
    daemon: simple
    plugs:
      - network-bind

  mongod:
    command: mongod
    plugs:
      - network
      - network-bind
      
  mongos:
    command: mongos
    plugs:
      - network
      - network-bind

  mongo:
    command: mongo
    plugs:
      - network

  # Tools
  mongodump:
    command: mongodump
    plugs:
      - network

  mongorestore:
    command: mongorestore
    plugs:
      - network

  mongostat:
    command: mongostat
    plugs:
      - network

  mongotop:
    command: mongotop
    plugs:
      - network

parts:
  wrappers:
    plugin: dump
    source: snap/local/
    source-type: local
  mongo-tools:
    source: https://github.com/mongodb/mongo-tools
    source-type: git
    source-tag: "r4.2.11"
    plugin: go
    build-packages:
      - libpopt0
      - rsync
      - pkg-config
      - libssl-dev
      - libpcap0.8-dev
      - libsasl2-dev
    stage-packages:
      - libssl1.1
      - libpcap0.8
      - libsasl2-2
    go-channel: 1.15/stable
    override-build: |
      mongo_tools="mongodump mongorestore mongotop mongostat"
      export GOPATH=$(realpath ../)
      src_dir=$GOPATH/src/github.com/mongodb/mongo-tools
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin/
      mkdir -p $src_dir
      rsync -r --remove-source-files --exclude=github.com ../src/* $src_dir
      cd $src_dir
      go get -d github.com/mongodb/mongo-tools-common/...
      go get -d $src_dir/...
      . $src_dir/set_goenv.sh
      for tool in ${mongo_tools}; do
          go build -v $(buildflags) -ldflags "-s -w $(print_ldflags)" -tags="ssl sasl" -o ${SNAPCRAFT_PART_INSTALL}/bin/$tool ./$tool/main
      done

  mongo:
    source: https://github.com/mongodb/mongo
    source-type: git
    source-tag: "r4.4.2"
    plugin: nil
    stage-packages:
      - libssl1.1
      - libcurl4
      - libstemmer0d
      - zlib1g
      - libsnappy1v5
      - libyaml-cpp0.6
      - libpcre3
      - libpcrecpp0v5
      - libboost-system-dev
      - libboost-iostreams-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libgoogle-perftools4
    build-packages:
      # isn't available on s390x, only needed on the rest anyway.
      - try:
          - libgoogle-perftools-dev
      - libssl-dev
      - libcurl4-openssl-dev
      # python packages cribbed from deb, might need changed.
      - python-typing
      - python3-cheetah
      - python3-pip
      - python3-pkg-resources
      - python3-pymongo
      - python3-yaml
      - python3-psutil
      # I think these and some of the above will be needed as staging packages too (for when its installed and being run).
      # - python-requests
      # - python-subprocess32
      # Package from deb, note scons arg above.
      - libstemmer-dev
      - zlib1g-dev
      - libsnappy-dev
      - libyaml-cpp-dev
      - libpcre3-dev
      - libboost-iostreams-dev
      # packages from the mongodb wiki/doc
      - build-essential
      - libboost-log-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-thread-dev
      # required packages
      - valgrind

    override-build: |
      update-alternatives --install /usr/bin/python python /usr/bin/python3 1

      # don't care: --server-js=off
      # Use system tcmalloc as it's more 'trusted' and would be updated by kernel/security team.
      SCONSFLAGS="--use-system-tcmalloc --disable-warnings-as-errors --use-system-pcre --use-system-snappy --use-system-zlib --use-system-valgrind --use-system-stemmer --use-system-yaml --ssl"
      arch=$(uname -m)
      if [ $arch = "aarch64" ]; then
          ccflags_arg="CCFLAGS=-march=armv8-a+crc"
      else
          ccflags_arg=""
      fi

      if [ $arch = "s390x" ]; then
          SCONSFLAGS="$SCONSFLAGS --allocator=system"
      else
          SCONSFLAGS="$SCONSFLAGS --allocator=tcmalloc"
      fi
      export SCONSFLAGS
      export DESTDIR=$SNAPCRAFT_PART_INSTALL

      python3 buildscripts/scons.py install-core $ccflags_arg

      # Strip binaries down to a usable size.
      for file in $SNAPCRAFT_PART_BUILD/build/install/bin/mongo*;
          do strip -s $file;
      done
      mv $SNAPCRAFT_PART_BUILD/build/install/bin $SNAPCRAFT_PART_INSTALL/
